name: Minion
version: 3.0.0
api: 4.0.0
main: CLADevs\Minion\Loader
author: CLADevs
softdepend:
  - EconomyAPI
  - BedrockEconomy
commands:
  minion:
    permission: "minion.commands"
    description: "get the Minion Spawner!"

permissions:
  minion.commands:
    description: "/minion command permission"
    default: op
  minion.open.others:
    description: "Open other people minions"
    default: op
